---
- name: Verify
  hosts: localhost
  tasks:
    - name: Check if the starship cli exists
      stat:
        path: /usr/local/bin/starship
      register: starship_cli_facts

    - name: Check if Starship CLI is installed
      command: "which starship"
      register: starship_result
      ignore_errors: true

    - name: Print result
      debug:
        var: starship_result.stdout_lines

    - name: Fail if starship cli does not exist
      fail:
        msg: "Starship cli does not exist."
      when: not starship_cli_facts.stat.exists
